Fix/codex review12 24
Applifting/culture pull request #36
Opened 2024-12-16 11:54 UTC by martinbalak

We have a new version of our vision and mission. This is the updated version of our codex to be aligned with it

2025-01-07 11:30 UTC, Vratislav requested changes

2025-01-07 11:30 UTC, Vratislav commented on cs/applifters-codex.md
> +* Bez trochy štěstí není výkonů
Tenhle edit zvyšuje dvojznačnost sdělení.
Tohle by mohlo vyznít tak, že bez toho, abys měl štěstí (chápáno, že ti dopadaj věci), že není výkonů.

Ale původně je to myšleno tak, že bez toho, že jsi v životě/v práci šťastný, tak nemůžeš podávat dobrej výkon.

2025-01-07 12:04 UTC, martinbalak commented on cs/applifters-codex.md
> +* Bez trochy štěstí není výkonů
tzn raději bys tamměl Bez štěstí není výkonů? Než bez trochy štěstí není výkonů?

2025-01-08 18:44 UTC, martinbalak commented on cs/applifters-codex.md
> +* Bez trochy štěstí není výkonů
Abychom mohli odvádět dobrou práci, je potřeba, abychom byli spokojení v ní i v soukromém životě.

2025-01-13 13:56 UTC, merged